<?php
/**
 * Created by PhpStorm.
 * User: nhmayaou
 * Date: 12/02/17
 * Time: 00:32
 */

namespace Fideni\UserBundle\Controller;

use Fideni\UserBundle\Form\UserType;
use FOS\UserBundle\Controller\ProfileController as BaseController;
use FOS\UserBundle\Model\UserInterface;
use FOS\UserBundle\Model\UserManagerInterface;
use Symfony\Component\Finder\Exception\AccessDeniedException;
use Symfony\Component\HttpFoundation\Request;

class ProfileController extends BaseController
{

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function editAction(Request $request)
    {
        dump('inn override');
        $user = $this->getUser();
//        if (!is_object($user) || !$user instanceof UserInterface) {
//            throw new AccessDeniedException('This user does not have access to this section.');
//        }
//        return parent::editAction($request); // TODO: Change the autogenerated stub
        
        $form = $this->createForm(UserType::class, $user);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var $userManager UserManagerInterface */
            $userManager = $this->get('fos_user.user_manager');

            $userManager->updateUser($user);
//dump($this->generateUrl('fos_user_profile_show'));die;
            return $this->redirectToRoute('fos_user_profile_show');
        }

        dump($form);
        return $this->render('@FOSUser/Profile/edit.html.twig', [
           'form' => $form->createView() 
        ]);
    }
}