easy_admin:
    site_name: 'Fideni Admin'
    design:
        brand_color: '#f58427'
        assets:
            favicon: '/media/cache/my_favicon/bundles/fidenicore/img/logo.jpeg'
    list:
        actions:
            - { name: 'show', label: '', icon: 'eye'}
            - { name: 'edit', label: '', icon: 'pencil'}
            - { name: 'delete', label: '', icon: 'trash'}
