fideni_core:
    resource: "@FideniCoreBundle/Resources/config/routing.yml"
    prefix:   /

fideni_user:
    resource: "@FideniUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@FideniCoreBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin


