fideni_core:
    resource: "@FideniCoreBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@FideniCoreBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin


