fideni_core:
    resource: "@FideniCoreBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"

easy_admin_bundle:
    resource: "@FideniCoreBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin
liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

