easy_admin:
    entities:
        Campaign:
            class: Fideni\CoreBundle\Entity\Campaign
            label: 'Gestion des campagnes de souscription'
            translation_domain: 'messages'
            form:
                fields:
                    - { property: sharePrice, label: 'app.admin.campaign.share_price'}
                    - { property: startDate, label: 'app.admin.campaign.start_date'}
                    - { property: endDate, label: 'app.admin.campaign.end_date'}
                    - { property: enabled, label: 'app.admin.campaign.enabled'}
            show:
                fields:
                    - { property: sharePrice, label: 'app.admin.campaign.share_price'}
                    - { property: startDate, label: 'app.admin.campaign.start_date'}
                    - { property: endDate, label: 'app.admin.campaign.end_date'}
                    - { property: enabled, label: 'app.admin.campaign.enabled'}