easy_admin:
    entities:
        Share:
            class: Fideni\CoreBundle\Entity\Share
            label: 'Gestion des actions'
            disabled_actions: ['new', 'edit', 'delete']
            list:
                title: 'Les dernières actions'
                fields:
                    - id
                    - { property: nominalValue, label: app.admin.share.nominal_value }
                    - { property: acquisitionDate, label: app.admin.share.acquisition_date }
                    - { property: price, label: app.admin.share.price }
                    - { property: subscription, label: app.admin.share.subscription, sortable: false }
                    - { property: partner, label: app.admin.share.partner }

