easy_admin:
    entities:
        Subscription:
            class: Fideni\CoreBundle\Entity\Subscription
            label: 'Souscription à une action'
            new:
                title: "Attribution d'actions à un associé"
            edit:
                title: "Modification suscription"
#            list:
#                fields:
#                    - inherit
#                    - { property: 'user', label: 'app.admin.subscription.user', type_options: {property: name_surname} }
            form:
                fields:
                    - { property: 'campaign', label: 'app.admin.subscription.campaign', type: 'Fideni\CoreBundle\Form\CampaignType'}
                    - { property: 'shares', label: 'app.admin.subscription.shares', type: 'collection', type_options: { entry_tpe: 'Fideni\CoreBundle\Form\ShareType', by_reference: false, allow_add: true, allow_delete: true}}
                    - { property: 'user', label: 'app.admin.subscription.user', type_options: {property: name_surname} }
