easy_admin:
    entities:
        Subscription:
            class: Fideni\CoreBundle\Entity\Subscription
            label: 'Souscription à une action'
            new:
                title: "Attribution d'actions à un associé"
            edit:
                title: "Modification suscription"
#            list:
#                fields:
#                    - inherit
#                    - { property: 'user', label: 'app.admin.subscription.user', type_options: {property: name_surname} }
            form:
                fields:
                    - { property: 'campaignNumber', label: 'app.admin.subscription.campaign_number' }
                    - { property: 'sharePrice', label: 'app.admin.subscription.share_price' }
                    - { property: 'startDate', label: 'app.admin.subscription.start_date' }
                    - { property: 'endDate', label: 'app.admin.subscription.end_date' }
                    - { property: 'sharePrice', label: 'app.admin.subscription.share_price' }
                    - { property: 'shareNumber', label: 'app.admin.subscription.share_number' }
                    - { property: 'user', label: 'app.admin.subscription.user', type_options: {property: name_surname} }