easy_admin:
    entities:
        Subscription:
            class: Fideni\CoreBundle\Entity\Subscription
            label: 'Souscription à une action'
            new:
                title: "Attribution d'actions à un associé"
            edit:
                title: "Modification souscription"
            list:
                fields:
                    - id
                    - { property: 'user', label: 'app.admin.subscription.user'}
                    - { property: 'campaign', label: 'app.admin.subscription.campaign'}
                    - { property: 'sharePrice', label: 'app.admin.subscription.share_price'}
                    - { property: 'shareNumber', label: 'app.admin.subscription.share_number' }
            form:
                fields:
                    - { property: 'campaign', label: 'app.admin.subscription.campaign', type: 'Fideni\CoreBundle\Form\CampaignType'}
                    - { property: 'nbShares', label: 'app.admin.subscription.nb_shares'}
                    - { property: 'user', label: 'app.admin.subscription.user' }