easy_admin:
    entities:
        User:
            class: Fideni\UserBundle\Entity\User
            label: 'Associés'
            list:
                title: 'Associés'
                actions:
                    - { name: 'show', label: '', icon: 'eye'}
                    - { name: 'edit', label: '', icon: 'pencil'}
                    - { name: 'delete', label: '', icon: 'trash'}
                    - { name: 'subscription', label: app.admin.user.subscription }
                    - { name: 'userShares', label: app.admin.user.actions, icon: money }
#                    - { name: cession, label: app.admin.user.cession }
                fields:
                    - { property: 'name', label: 'app.admin.user.name'}
                    - { property: 'surname', label: 'app.admin.user.surname' }
                    - email
                    - { property: tel1, label: app.admin.user.tel }
                    - { property: last_login, type: datetime}
                    - { property: enabled, label: app.admin.user.enabled }
            show:
                title: Detail associé
                fields:
                    - id
                    - { property: 'photo', type: 'image', base_path: '%user_uploads_directory%' }
                    - username
                    - email
                    - name
                    - surname
                    - { property: last_login, type: datetime }
                    - enabled
                    - formation
                    - birthDate
                    - country
                    - city
                    - street
                    - { property: 'tel1', label: 'app.admin.user.tel' }
                    - { property: roles, label: Droits }
                    - { property: 'heirs', template: 'heirs.html.twig', label: app.admin.user.heirs}
            new:
                title: 'Ajouter un associé'
                label: 'Ajouter Associé'
                actions:
                    - { name: 'new', label: 'Ajouter', icon: 'search' }
                fields:
                    - '-formation'
                    - '-heirs'
                    - '-birthDate'
            edit:
                title: 'Modifier'
                fields:
                    - '-password'
            form:
                fields:
                    - username
                    - email
                    - { property: photoFile, type: 'vich_image' }
                    - { property: password, type: password }
                    - { property: 'name', label: 'app.admin.user.name'}
                    - { property: 'surname', label: 'app.admin.user.surname' }
                    - formation
                    - { property: birthDate, type: 'Symfony\Component\Form\Extension\Core\Type\BirthdayType',  label: 'app.admin.user.birth_date'  }
                    - {property: country , type: 'Symfony\Component\Form\Extension\Core\Type\CountryType'}
                    - city
                    - street
                    - { property: 'tel1', label: 'app.admin.user.tel1' }
                    - 'roles'
                    - { property: 'heirs', label: 'app.admin.user.heirs',type: 'collection', type_options: { entry_type: 'Fideni\UserBundle\Form\HeirType', by_reference: false, allow_add: true, allow_delete: true }}
