easy_admin:
    entities:
        User:
            class: Fideni\UserBundle\Entity\User
            list:
                title: 'Associés'
            edit:
                fields: [{property: 'heirs', template: 'heirs_edit.html.twig'}]
            show:
                fields: [{ property: 'heirs', template: 'heirs.html.twig'}]
            form:
                fields: [ { property: 'heirs', type: 'collection', type_options: { entry_type: 'Fideni\UserBundle\Form\HeirType' }}]
#                                    fields: [{ property: 'images', type: 'collection', type_options: { entry_type: 'AppBundle\Form\ImageType' }}]
