<?php

namespace Fideni\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CampaignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignRepository extends EntityRepository
{
    public function disable(){
        $this->createQueryBuilder('c')
             ->update()
             ->set('c.enabled', 0)
            ->getQuery()->execute();
    }

    public function getLastEnabled(){
       $result = $this->createQueryBuilder('c')
             ->select('c')
            ->where('c.enabled = 1')
            ->orderBy('c.id', 'desc')
            ->getQuery()->getResult();

        if(!empty($result)){
            return $result[0];
        }

        return null;
    }
}
