<?php

namespace Fideni\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CampaignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignRepository extends EntityRepository
{
    public function disable(){
        $this->createQueryBuilder('c')
             ->update()
             ->set('c.enabled', 0)
//            ->setParameter(enabled, 0)
            ->getQuery()->execute();
    }
}
