<?php

namespace Fideni\CoreBundle\Repository;

/**
 * CessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CessionRepository extends \Doctrine\ORM\EntityRepository
{
}
