<?php

namespace Fideni\CoreBundle\Repository;

/**
 * FideniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FideniRepository extends \Doctrine\ORM\EntityRepository
{
}
