<?php

namespace Fideni\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * ShareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShareRepository extends EntityRepository
{
    /**
     * @param null $userId
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getUserShareBuilder($userId=null)
    {
        $qb = $this->createQueryBuilder('s')
                   ->select('s');

        if(!is_null($userId)){
            $qb->innerJoin('s.subscription', 'sub', 'WITH', 'sub.user = :userId')
                ->setParameter('userId', $userId);
        }

        return $qb;
    }
}
