fideni_core_homepage:
    path:     /
    defaults: { _controller: FideniCoreBundle:Default:index }

projects:
    path:     /projects
    defaults: { _controller: FideniCoreBundle:Ajax:projects }

fideni_user_profile_show:
    path: /profile/{id}
    defaults: { _controller: FideniUserBundle:UserProfile:show, id: null }
    requirements:
        id: \d*

fideni_user_profile_edit:
    path: /profile/edit
    defaults: { _controller: FideniUserBundle:UserProfile:edit }

ajax_global_stats:
    path: /ajax-global-stats
    defaults: { _controller: FideniCoreBundle:Ajax:getGlobalStats }

ajax_get_users:
    path: /ajax-get-all-users
    defaults: { _controller: FideniCoreBundle:Ajax:getAllUsers }

ajax_get_projects:
    path: /ajax-get-project/{status}
    defaults: { _controller: FideniCoreBundle:Ajax:projects }
    requirements:
        status: \w+

ajax_get_user_shares:
    path: /ajax-user-shares
    defaults: { _controller:  FideniCoreBundle:Ajax:getUserShare }
