services:
    fideni_core.object_serializer:
        class: Fideni\CoreBundle\Services\ObjectSerializer
    fideni_core.image_manager:
        class: Fideni\CoreBundle\Services\ImageManager
    image_upload.event_listener:
        class: Fideni\CoreBundle\EventListeners\VichEventListener
        arguments: ['@fideni_core.image_manager']
        tags:
            - { name: kernel.event_listener, event: vich_uploader.post_upload, method: onPostUpload }
#    fideni_core.data_formatter:
#        class: Fideni\CoreBundle\Services\DataFormatter
#        arguments: ['@fideni_core.object_serializer', '@liip_imagine.controller', '%upload_dir%']