<?php

namespace Fideni\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends EntityRepository
{
}
