<?php

namespace Fideni\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function count(){
        return $this->createQueryBuilder('u')
              ->select('count(u.id)')
              ->getQuery()->getSingleScalarResult();
    }
}
