<?php

namespace Proxies\__CG__\Fideni\CoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Project extends \Fideni\CoreBundle\Entity\Project implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Fideni\\CoreBundle\\Entity\\Project' . "\0" . 'id', '' . "\0" . 'Fideni\\CoreBundle\\Entity\\Project' . "\0" . 'legalForm', '' . "\0" . 'Fideni\\CoreBundle\\Entity\\Project' . "\0" . 'compagnyAsset', '' . "\0" . 'Fideni\\CoreBundle\\Entity\\Project' . "\0" . 'fideniShare', '' . "\0" . 'Fideni\\CoreBundle\\Entity\\Project' . "\0" . 'numberOfPartner', '' . "\0" . 'Fideni\\CoreBundle\\Entity\\Project' . "\0" . 'country', '' . "\0" . 'Fideni\\CoreBundle\\Entity\\Project' . "\0" . 'city', '' . "\0" . 'Fideni\\CoreBundle\\Entity\\Project' . "\0" . 'tel', '' . "\0" . 'Fideni\\CoreBundle\\Entity\\Project' . "\0" . 'fax', '' . "\0" . 'Fideni\\CoreBundle\\Entity\\Project' . "\0" . 'leader', '' . "\0" . 'Fideni\\CoreBundle\\Entity\\Project' . "\0" . 'founded');
        }

        return array('__isInitialized__', '' . "\0" . 'Fideni\\CoreBundle\\Entity\\Project' . "\0" . 'id', '' . "\0" . 'Fideni\\CoreBundle\\Entity\\Project' . "\0" . 'legalForm', '' . "\0" . 'Fideni\\CoreBundle\\Entity\\Project' . "\0" . 'compagnyAsset', '' . "\0" . 'Fideni\\CoreBundle\\Entity\\Project' . "\0" . 'fideniShare', '' . "\0" . 'Fideni\\CoreBundle\\Entity\\Project' . "\0" . 'numberOfPartner', '' . "\0" . 'Fideni\\CoreBundle\\Entity\\Project' . "\0" . 'country', '' . "\0" . 'Fideni\\CoreBundle\\Entity\\Project' . "\0" . 'city', '' . "\0" . 'Fideni\\CoreBundle\\Entity\\Project' . "\0" . 'tel', '' . "\0" . 'Fideni\\CoreBundle\\Entity\\Project' . "\0" . 'fax', '' . "\0" . 'Fideni\\CoreBundle\\Entity\\Project' . "\0" . 'leader', '' . "\0" . 'Fideni\\CoreBundle\\Entity\\Project' . "\0" . 'founded');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Project $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLegalForm($legalForm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLegalForm', array($legalForm));

        return parent::setLegalForm($legalForm);
    }

    /**
     * {@inheritDoc}
     */
    public function getLegalForm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLegalForm', array());

        return parent::getLegalForm();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompagnyAsset($compagnyAsset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompagnyAsset', array($compagnyAsset));

        return parent::setCompagnyAsset($compagnyAsset);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompagnyAsset()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompagnyAsset', array());

        return parent::getCompagnyAsset();
    }

    /**
     * {@inheritDoc}
     */
    public function setFideniShare($fideniShare)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFideniShare', array($fideniShare));

        return parent::setFideniShare($fideniShare);
    }

    /**
     * {@inheritDoc}
     */
    public function getFideniShare()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFideniShare', array());

        return parent::getFideniShare();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberOfPartner($numberOfPartner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberOfPartner', array($numberOfPartner));

        return parent::setNumberOfPartner($numberOfPartner);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberOfPartner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberOfPartner', array());

        return parent::getNumberOfPartner();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry($country)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', array($country));

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', array());

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', array($city));

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', array());

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel($tel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel', array($tel));

        return parent::setTel($tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel', array());

        return parent::getTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setFax($fax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', array($fax));

        return parent::setFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', array());

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setLeader($leader)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeader', array($leader));

        return parent::setLeader($leader);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeader()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeader', array());

        return parent::getLeader();
    }

    /**
     * {@inheritDoc}
     */
    public function getFounded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFounded', array());

        return parent::getFounded();
    }

    /**
     * {@inheritDoc}
     */
    public function setFounded($founded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFounded', array($founded));

        return parent::setFounded($founded);
    }

}
